"""Added user table

Revision ID: 38908818eb7e
Revises: 
Create Date: 2020-10-30 18:15:19.310804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38908818eb7e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mail', sa.String(length=200), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
